name: 'Cepler'
description: 'Run cepler commands on a repo'
inputs:
  repository:
    description: 'Repository'
    required: true
    default: "."
  config_path:
    description: 'Path to cepler.yml file in repository'
    required: true
    default: 'cepler.yml'
  environment:
    description: 'The environment name to run against'
    required: true
  prepare:
    description: 'Should prepare'
    default: false
  record:
    description: 'Should record'
    default: false
outputs:
  needs_deploying:
    description: 'Wether the check command returned 0'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    CEPLER_CONF: ${{ inputs.config_path }}
    CEPLER_ENVIRONMENT: ${{ inputs.environment }}
    PREPARE: ${{ inputs.prepare }}
    RECORD: ${{ inputs.record }}
  args:
    - ${{ inputs.repository }}
